services:
  client:
    container_name: maintex-client-beta
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: 2
        reservations:
          memory: 1g
          cpus: 2
    ports:
      - "8808:8808"