services:
  client:
    container_name: maintex-client-beta
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_NODE_ENV=${VITE_NODE_ENV:-production}
        - VITE_PORT=${VITE_PORT:-8808}
        - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
        - VITE_DEBUG=${VITE_DEBUG:-false}
        - VITE_API_URL=${VITE_API_URL}
        - VITE_AUTH_URL=${VITE_AUTH_URL}
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_STORAGE_URL=${VITE_STORAGE_URL}
        - VITE_APP_SECRET_KEY=${VITE_APP_SECRET_KEY}
        - VITE_APP_STORAGE_SECRET_KEY=${VITE_APP_STORAGE_SECRET_KEY}
        - VITE_APP_STORAGE_API_KEY=${VITE_APP_STORAGE_API_KEY}
        - VITE_TOMTOM_API_KEY=${VITE_TOMTOM_API_KEY}
        - VITE_TOMTOM_STYLE_DARK=${VITE_TOMTOM_STYLE_DARK}
        - VITE_TOMTOM_STYLE_LIGHT=${VITE_TOMTOM_STYLE_LIGHT}
        - VITE_SOCKET_URL=${VITE_SOCKET_URL}
        - VITE_DOCS_URL=${VITE_DOCS_URL}
        - VITE_DEVELOPER_URL=${VITE_DEVELOPER_URL}
        - VITE_API_AI_URL=${VITE_API_AI_URL}
        - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
        - ENABLE_TANSTACK_ROUTE_GENERATION=${ENABLE_TANSTACK_ROUTE_GENERATION:-true}
    environment:
      - VITE_NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 8g
          cpus: 4
        reservations:
          memory: 4g
          cpus: 2
    ports:
      - "8808:8808"