services:
  client:
    container_name: maintex-client
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_NODE_ENV=${VITE_NODE_ENV}
      - VITE_PORT=${VITE_PORT}
      - VITE_APP_VERSION=${VITE_APP_VERSION}
      - VITE_DEBUG=${VITE_DEBUG}
      - VITE_APP_SECRET_KEY=${VITE_APP_SECRET_KEY}

      - VITE_API_URL=${VITE_API_URL}
      - VITE_API_AI_URL=${VITE_API_AI_URL}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_AUTH_URL=${VITE_AUTH_URL}
      - VITE_DOCS_URL=${VITE_DOCS_URL}
      - VITE_SOCKET_URL=${VITE_SOCKET_URL}

      - VITE_DEVELOPER_URL=${VITE_DEVELOPER_URL}

      #Tomtom
      - VITE_TOMTOM_API_KEY=${VITE_TOMTOM_API_KEY}
      - VITE_TOMTOM_STYLE_DARK=${VITE_TOMTOM_STYLE_DARK}
      - VITE_TOMTOM_STYLE_LIGHT=${VITE_TOMTOM_STYLE_LIGHT}

      #Gemini
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}

    ports:
      - "8808:8808"